### PR TITLE
Fixed sorting by 'Last Updated' field for games list

### LINKED ISSUE #841: Issue with "Last Updated" sorting
Sorting Game List by Last Updated (IDs `6` and `16`) don't seem to follow an order.

Game Boy Color for example:
image

### PR DESCRIPTION
**Pull request by anegoda1995**
Fixes #841

### CODE REVIEW

File: lib/database/game.php [hunk 1]
```diff
@@ -420,10 +420,10 @@ function getGamesListByDev($dev, $consoleID, &$dataOut, $sortBy, $ticketsFlag =
             break;
 
         case 6:
-            $query .= "ORDER BY gd.ConsoleID, ach.DateModified DESC, Title ";
+            $query .= "ORDER BY gd.ConsoleID, MAX(ach.DateModified) DESC, Title ";
```
Comment (luchaos) [inline lib/database/game.php:423]: Good find 👍 

As @Jamiras pointed out this could be done by reusing the `DateModified` column alias, too, to keep it simpler.

See https://github.com/RetroAchievements/RAWeb/blob/master/lib/database/game.php#L357

Maybe a better name for that alias would be fitting - like `SetDateModified` as it's about the last change in a game's achievement set rather than a game's own metadata. Not that important, though.

**Review by luchaos — CHANGES_REQUESTED** [review]

**Review by luchaos — APPROVED** [review]
