### PR TITLE
fix display of images on game compare page

### LINKED ISSUE #1217: Game Compare: other user's achievement icons don't show properly
When comparing your scores to another user, all of the icons for THEIR achievements are always greyed out, even if it shows the time and date when they earned them. Here's a screenshot of what it looks like: 
rabug

### PR DESCRIPTION
**Pull request by Jamiras**
fixes #1217

### CODE REVIEW

File: public/gamecompare.php [hunk 1]
```diff
@@ -196,7 +196,7 @@
                         $rightSoftcoreAwardedPoints += $achPoints;
                         echo "<small class='smalldate'>$awardedRight</small>";
                     }
-                    echo achievementAvatar($nextAch, label: false, icon: $badgeName . "_lock", iconSize: $iconSize, iconClass: 'awardremote', tooltip: false);
+                    echo achievementAvatar($nextAch, label: false, icon: $badgeName, iconSize: $iconSize, iconClass: isset($awardedHCRight) ? 'goldimage' : '', tooltip: false);
```
Comment (Jamiras) [inline public/gamecompare.php:199]: `_lock` was incorrectly added by https://github.com/RetroAchievements/RAWeb/pull/1149/files#diff-1b3f2a3b9e72f81134ba1e00c5c39e9206122eb246ed2d1495c7ea923109d36bL199, but `awardremote` was there before. It doesn't seem to be defined, so I've replaced with the standard gold border for hardcore logic.

Comment (luchaos) [reply public/gamecompare.php:199]: Thanks! That was an oversight on my end

**Review by luchaos — APPROVED** [review]
