### PR TITLE
fix resetting progress from achievement page

### LINKED ISSUE #1116: Unable to reset achievement progress in RAWeb 2.0.0
image

I get this error when trying to reset all progress in a set or individual achievement progress.

### PR DESCRIPTION
**Pull request by Jamiras**
fixes #1116

### CODE REVIEW

File: public/achievementInfo.php [hunk 1]
```diff
@@ -231,11 +249,7 @@ function updateAchievementTypeFlag(typeFlag) {
             echo "<div class='devbox mb-3'>";
             echo "<span onclick=\"$('#resetboxcontent').toggle(); return false;\">Reset Progress ▼</span>";
             echo "<div id='resetboxcontent' style='display: none'>";
-            echo "<form action='/request/user/reset-achievements.php' method='post' onsubmit='return confirm(\"Are you sure you want to reset this progress?\")'>";
-            echo csrf_field();
-            echo "<input type='hidden' name='a' value='$achievementID'>";
```
Comment (luchaos) [inline public/achievementInfo.php:236]: looks like the input name was the culprit there

Comment (Jamiras) [reply public/achievementInfo.php:236]: Yep. But after fixing that, the submission would page turn to the javascript response, which is why I replaced the form with an ajax call.

File: public/achievementInfo.php [hunk 2]
```diff
@@ -146,6 +146,24 @@ function updateAchievementTypeFlag(typeFlag) {
     }
     </script>
 <?php endif ?>
+
+<?php if ($achievedLocal): ?>
```
Comment (luchaos) [inline public/achievementInfo.php:150]: personally i'd opt for default form post request behaviour instead of emulating it via javascript.
i think adjusting the input name should be enough?

Comment (Jamiras) [reply public/achievementInfo.php:150]: reset-achievements.php returns JSON, not a web page or redirect.

File: public/achievementInfo.php (hunk 1 above)
Comment (luchaos) [reply public/achievementInfo.php:236]: oh, i see. disregard my other comment then. this mix of json and default form requests is a mess 😅

**Review by luchaos — APPROVED** [review]
